# General Data Cleaning


## Data import

In [ ]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("melb_data.csv")
data

Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S   
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2         Abbotsford      5 Charles St      3    h  1465000.0     SP   
3         Abbotsford  40 Federation La      3    h   850000.0     PI   
4         Abbotsford       55a Park St      4    h  1600000.0     VB   
...              ...               ...    ...  ...        ...    ...   
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S   
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP   
13577   Williamstown       83 Power St      3    h  1170000.0      S   
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI   
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP   

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0   
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0   
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0   
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0   
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0   
...         ...         ...       ...       ...  ...       ...  ...       ...   
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0   
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0   
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0   
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0   
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0   

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN        NaN        Yarra -37.79960   144.99840   
1              79.0     1900.0        Yarra -37.80790   144.99340   
2             150.0     1900.0        Yarra -37.80930   144.99440   
3               NaN        NaN        Yarra -37.79690   144.99690   
4             142.0     2014.0        Yarra -37.80720   144.99410   
...             ...        ...          ...       ...         ...   
13575           NaN     1981.0          NaN -37.90562   145.16761   
13576         133.0     1995.0          NaN -37.85927   144.87904   
13577           NaN     1997.0          NaN -37.85274   144.88738   
13578         157.0     1920.0          NaN -37.85908   144.89299   
13579         112.0     1920.0          NaN -37.81188   144.88449   

                       Regionname Propertycount  
0           Northern Metropolitan        4019.0  
1           Northern Metropolitan        4019.0  
2           Northern Metropolitan        4019.0  
3           Northern Metropolitan        4019.0  
4           Northern Metropolitan        4019.0  
...                           ...           ...  
13575  South-Eastern Metropolitan        7392.0  
13576        Western Metropolitan        6380.0  
13577        Western Metropolitan        6380.0  
13578        Western Metropolitan        6380.0  
13579        Western Metropolitan        6543.0  

[13580 rows x 21 columns]

In [3]:
data.YearBuilt

0           NaN
1        1900.0
2        1900.0
3           NaN
4        2014.0
          ...  
13575    1981.0
13576    1995.0
13577    1997.0
13578    1920.0
13579    1920.0
Name: YearBuilt, Length: 13580, dtype: float64

# Address missing values

In [4]:

missing_value_num = data.YearBuilt.isnull().sum()
missing_value_num

5375

In [5]:
total_value_num = np.product(data.YearBuilt.shape)
missing_value_num/total_value_num

0.3958026509572901

In [6]:
# the easiest way

cleaned_data = data.dropna(subset = ['YearBuilt'])
cleaned_data

Suburb          Address  Rooms Type      Price Method   SellerG  \
1         Abbotsford  25 Bloomburg St      2    h  1035000.0      S    Biggin   
2         Abbotsford     5 Charles St      3    h  1465000.0     SP    Biggin   
4         Abbotsford      55a Park St      4    h  1600000.0     VB    Nelson   
6         Abbotsford     124 Yarra St      3    h  1876000.0      S    Nelson   
7         Abbotsford    98 Charles St      2    h  1636000.0      S    Nelson   
...              ...              ...    ...  ...        ...    ...       ...   
13575  Wheelers Hill     12 Strada Cr      4    h  1245000.0      S     Barry   
13576   Williamstown    77 Merrett Dr      3    h  1031000.0     SP  Williams   
13577   Williamstown      83 Power St      3    h  1170000.0      S     Raine   
13578   Williamstown     96 Verdon St      4    h  2500000.0     PI   Sweeney   
13579     Yarraville       6 Agnes St      4    h  1285000.0     SP   Village   

             Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
1       4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0   
2       4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0   
4       4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0   
6       7/05/2016       2.5    3067.0  ...       2.0  0.0     245.0   
7       8/10/2016       2.5    3067.0  ...       1.0  2.0     256.0   
...           ...       ...       ...  ...       ...  ...       ...   
13575  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0   
13576  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0   
13577  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0   
13578  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0   
13579  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0   

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
1              79.0     1900.0        Yarra -37.80790   144.99340   
2             150.0     1900.0        Yarra -37.80930   144.99440   
4             142.0     2014.0        Yarra -37.80720   144.99410   
6             210.0     1910.0        Yarra -37.80240   144.99930   
7             107.0     1890.0        Yarra -37.80600   144.99540   
...             ...        ...          ...       ...         ...   
13575           NaN     1981.0          NaN -37.90562   145.16761   
13576         133.0     1995.0          NaN -37.85927   144.87904   
13577           NaN     1997.0          NaN -37.85274   144.88738   
13578         157.0     1920.0          NaN -37.85908   144.89299   
13579         112.0     1920.0          NaN -37.81188   144.88449   

                       Regionname Propertycount  
1           Northern Metropolitan        4019.0  
2           Northern Metropolitan        4019.0  
4           Northern Metropolitan        4019.0  
6           Northern Metropolitan        4019.0  
7           Northern Metropolitan        4019.0  
...                           ...           ...  
13575  South-Eastern Metropolitan        7392.0  
13576        Western Metropolitan        6380.0  
13577        Western Metropolitan        6380.0  
13578        Western Metropolitan        6380.0  
13579        Western Metropolitan        6543.0  

[8205 rows x 21 columns]

In [7]:
from sklearn.impute import SimpleImputer

In [8]:
# imputation

imputer = SimpleImputer(strategy = 'mean')
year_built = imputer.fit_transform(pd.DataFrame(data.YearBuilt))
print(year_built)

[[1964.68421694]
 [1900.        ]
 [1900.        ]
 ...
 [1997.        ]
 [1920.        ]
 [1920.        ]]


In [9]:
# expanded imputation

data.YearBuilt_Missing = data.YearBuilt.isnull()
print(data.YearBuilt_Missing)

0         True
1        False
2        False
3         True
4        False
         ...  
13575    False
13576    False
13577    False
13578    False
13579    False
Name: YearBuilt, Length: 13580, dtype: bool


C:\Users\xmw5190\AppData\Local\Temp\ipykernel_4392\1955547215.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.YearBuilt_Missing = data.YearBuilt.isnull()


# Scaling and Normalization

In [11]:
from scipy import stats

# for min_max scaling
from mlxtend.preprocessing import minmax_scaling

# plotting modules
import seaborn as sns
import matplotlib.pyplot as plt


In [20]:
print(data.Price)
scaled_price = minmax_scaling(data.Price, columns = [0])
scaled_price

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...    
13575    1245000.0
13576    1031000.0
13577    1170000.0
13578    2500000.0
13579    1285000.0
Name: Price, Length: 13580, dtype: float64


array([[0.15647785],
       [0.10656197],
       [0.15479529],
       ...,
       [0.12170499],
       [0.27089176],
       [0.1346046 ]])

In [23]:
normalized_price = stats.boxcox(data.Price)[0]
print(normalized_price)


[6.9659757  6.89560086 6.96401128 ... 6.92005523 7.0640039  6.93852264]


# Parsing Dates

In [24]:
import datetime

In [35]:
data.Date.dtype
data.Date

0         3/12/2016
1         4/02/2016
2         4/03/2017
3         4/03/2017
4         4/06/2016
            ...    
13575    26/08/2017
13576    26/08/2017
13577    26/08/2017
13578    26/08/2017
13579    26/08/2017
Name: Date, Length: 13580, dtype: object

In [49]:
data.date_parsed = pd.to_datetime(data.Date, format = "%d/%m/%Y")
data.date_parsed

In [48]:
other_date_type = "12-03-2016"
other_date_example = pd.to_datetime(other_date_type, format = "%m-%d-%Y")
other_date_example

Timestamp('2016-12-03 00:00:00')

In [52]:
year = data.date_parsed.dt.year
year

0        2016
1        2016
2        2017
3        2017
4        2016
         ... 
13575    2017
13576    2017
13577    2017
13578    2017
13579    2017
Name: Date, Length: 13580, dtype: int64

# Character Encoding

In [64]:
string = "This is the euro symbol: €"
string = string.encode("utf-8")
print(string)


b'This is the euro symbol: \xe2\x82\xac'


In [57]:
string = string.decode("utf-8")
print(string)

This is the euro symbol: €


In [59]:
string = string.decode("ascii")
print(string)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)

In [66]:
string = string.decode("ascii", errors = 'replace')
print(string)

This is the euro symbol: ���


In [67]:
data.to_csv('utf8_encoding_file.csv', encoding = 'utf-8')